config/routes.rb
Rails.application.routes.draw do
  # get 'search/index'
  # get 'search/search'
  get 'search' => 'seaches#search'
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'
  get 'home/about'

  resources :books, only: [:new, :create, :index, :show, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: %i[create edit update destroy]
  end

  resources :users, only: [:show, :edit, :update, :index]
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    unless @book.favorited_by?(current_user)
      favorite = current_user.favorites.new(book_id: @book.id)
      favorite.save
      # redirect_back(fallback_location:root_path) #直前のビューページにリダイレクト
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_back(fallback_location:root_path)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_like-button.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fas fa-heart", style='color: red;'></i>
        <%= book.favorites.count %>
    <% end %>

<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true  do %>
    <i class="far fa-heart"></i>
    <%= book.favorites.count %>
  <% end %>

<% end %>

app/views/favorites/create.js.erb
$("#like-button_<%= @book.id %>").html("<%= j(render 'favorites/like-button', book: @book ) %>");

app/views/favorites/destroy.js.erb
$("#like-button_<%= @book.id %>").html("<%= j(render 'favorites/like-button', book: @book ) %>");