config/routes.rb
Rails.application.routes.draw do
  # get 'search/index'
  # get 'search/search'
  get 'search' => 'seaches#search'
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'
  get 'home/about'

  resources :books, only: [:new, :create, :index, :show, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: %i[create edit update destroy]
  end

  resources :users, only: [:show, :edit, :update, :index]
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  attachment :profile_image

  validates :name, presence: true,
                   length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def self.search(search,word)
      if search == "forward_match"
        @user = User.where("name LIKE?","#{word}%")
      elsif search == "backward_match"
        @user = User.where("name LIKE?","%#{word}")
      elsif search == "perfect_match"
        @user = User.where("#{word}")
      elsif search == "partial_match"
        @user = User.where("name LIKE?","%#{word}%")
      else
        @user = User.all
      end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   before_action :authenticate_user!

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
       redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
     if  @user.update(user_params)
       flash[:notice] = 'You have updated successfully.'
         redirect_to user_path(@user.id)
     else
        render "edit"
     end
  end
  
  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
     user == current_user
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(user) %>
  <div id="follow_form">
  <% if current_user.following?(user) %>
    <%= render 'users/unfollow',user: user %>
  <% else %>
    <%= render 'users/follow',user: user %>
  <% end %>
  </div>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  follows
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
  </a>
  <br>
  followers
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
	  <div class="col-md-3">
        <h2>User info</h2>

        <% if @user.errors.any? %>
              <h3><%= @user.errors.count %>error prohibited this book from being saved:</h3>
            <% @user.errors.full_messages.each do |message| %>
              <p><%= message %></p>
            <% end %>
        <% end %>
        <br>
          <%= form_with model:@user, local:true do |f| %>
            <label >Name</label>
          <%= f.text_field :name, autofocus: true%>
        <br>
        <br>
            <label>Image</label>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
        <br>
            <label for="user_introduction">Introduction</label>
              <%= f.text_area :introduction %>
        <br>
        <br>
              <%= f.submit "Update User" %>
          <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render 'books/list', book:@book, user:@user %>
    </div>
    <div class="col-xs-9">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40,  fallback: "no_image.jpg",size: "40x40" %></td>
              <td><%= user.name %></td>
              <td>follows<%= user.followings.count %></td>
              <td>followers<%= user.followers.count %></td>
              <td><%= render 'follow_form',user: user %></td>
              <td><%= link_to 'Show', user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
   </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
  <% if flash[:notice] %>
    <div class="flash" >
      <%= flash[:notice] %>
    </div>
  <% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render 'books/list', book:@book, user:@user %>
    </div>
    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
              <tr>
                <td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40,  fallback: "no_image.jpg",size: "40x40" %></td>
                <td><%= link_to book.title, book_path(book) %></td>
                <td><%= book.body %></td>
                <td id='like-button_<% book.id %>'>
                  <%= render 'favorites/like-button', book: book %>
                </td>
                <td>
                  <%= render 'book_comments/index', book: book %>
                </td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div

app/views/users/show_follow.html.erb
<div class="container">
  <div class="row">
      <h2>Follow Users</h2>
      <table class="table">
        <tbody>
          <% @user.followings.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40,  fallback: "no_image.jpg",size: "40x40" %></td>
              <td><%= user.name %></td>
              <td>follows<%= user.followings.count %></td>
              <td>followers<%= user.followers.count %></td>
          <% end %>
        </tbody>
      </table>
   </div>
  </div>
</div>

app/views/users/show_follower.html.erb
<div class="container">
  <div class="row">
      <h2>Follower Users</h2>
      <table class="table">
        <tbody>
          <% @user.followers.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40,  fallback: "no_image.jpg",size: "40x40" %></td>
              <td><%= user.name %></td>
              <td>follows<%= user.followings.count %></td>
              <td>followers<%= user.followers.count %></td>
          <% end %>
        </tbody>
      </table>
   </div>
  </div>
</div>