config/routes.rb
Rails.application.routes.draw do
  # get 'search/index'
  # get 'search/search'
  get 'search' => 'seaches#search'
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'
  get 'home/about'

  resources :books, only: [:new, :create, :index, :show, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: %i[create edit update destroy]
  end

  resources :users, only: [:show, :edit, :update, :index]
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true,
                    length: { maximum: 200 }
  validates :body, presence: true,
                   length: { maximum: 200 }

  def self.search(search, word)
        if search == "forward_match"
          @book = Book.where("title LIKE?","#{word}%")
        elsif search == "backward_match"
          @book = Book.where("title LIKE?","%#{word}")
        elsif search == "perfect_match"
          @book = Book.where("#{word}")
        elsif search == "partial_match"
          @book = Book.where("title LIKE?","%#{word}%")
        else
          @book = Book.all
        end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

   before_action :authenticate_user!

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = 'Book was successfully created.'
        redirect_to book_path(@book.id)# 条件がtrueだったら処理1を行う
    else
      @user = current_user
      @books = Book.all
        render 'index' # 条件がfalseだったら処理2を行う
    end

  end

  def update
    @book = Book.find(params[:id])
     if  @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
        redirect_to book_path(@book.id)# 条件がtrueだったら処理1を行う
     else
        render "edit"# 条件がfalseだったら処理2を行う
     end
  end

  def destroy
    @book = Book.find_by(id: params[:id])
    @book.destroy
    redirect_to book_path
  end

  private

  def set_user
    @user = User.find([:id])
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
 <% if book.errors.any? %>   <!-- @book → book -->
   <h3><%= book.errors.count %>error prohibited this book from being saved:</h3>   <!-- @book → book -->
   <% book.errors.full_messages.each do |message| %>    <!-- @book → book -->
     <p><%= message %></p>
   <% end %>
 <% end %>


   <h2>User info</h2>
   <table class="table">
        <tbody>
           <%= attachment_image_tag user, :profile_image, :fill, 100, 100,  fallback: "no_image.jpg",size: "100x100" %>
             <tr>
              <th class="profile-name">name      <%= user.name %></th>          <!--@user → user-->
             </tr>
             <tr>
              <th class="profile-introduction">introduction      <%= user.introduction %></th>  <!--@user → user-->
             </tr>
             <tr>
              <th class="profile-stats"><%= render 'users/stats' %></th>
             </tr>
             <tr>
              <th class="profile-follow_form"><%= render 'users/follow_form',user: @user %></th>
             </tr>
        </tbody>
   </table>

   <% if user.id == current_user.id %>
     <p>
      <%= link_to edit_user_path(user) do %>
        <span class= "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_26318"></span>
      <% end %>
     </p>
   <% end %>
   <br>
   <br>
   <h2>New book</h2>
     <%= form_with model: book, local:true do |f| %>   <!-- @book → book -->
       <h5>Title</h5>
     <%= f.text_field :title, class:"col-xs-12" %>
       <h5>Opinion</h5>
     <%= f.text_area :body, class:"col-xs-12" %><br>
 <br>
 <br>
     <%= f.submit 'Create Book', class:"col-xs-12 btn btn-primary" %>
     <% end %>

app/views/books/edit.html.erb
<% if flash[:notice] %>
  <div class="flash" >
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="container">
  <div class="row">
	  <div class="col-md-6 col-md-offset-3">
      <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>error prohibited this book from being saved:</h3>
            <% @book.errors.full_messages.each do |message| %>
              <p><%= message %></p>
            <% end %>
        <% end %>

        <%= form_with model:@book, local:true do |f| %>

          <h5>Title</h5>
          <%= f.text_field :title, class:"col-xs-12" %>
          <h5>Opinion</h5>
          <%= f.text_area :body, class:"col-xs-12" %>
          <br>
          <br>
          <br>
          <%= f.submit "Update Book", class:"btn btn-primary col-xs-12" %>
        <% end %>
          <br>
          <br>
        <tr>
          <tb><%= link_to 'Show', book_path(@book.id) %></tb>
          |
          <tb><%= link_to 'Back', books_path %></tb>
        </tr>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render 'books/list', book:@book, user:@user %>
    </div>
    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
              <tr>
                <td><%= link_to user_path(book) do %>
                      <%= attachment_image_tag @user, :profile_image, :fill, 40, 40,  fallback: "no_image.jpg",size: "40x40" %>
                    <% end %>
                </td>
                <td><%= link_to book.title, book_path(book) %></td>
                <td><%= book.body %></td>

                <td>
                  <td id='like-button_<%= book.id %>'>
                  <%= render 'favorites/like-button', book: book %>
                </td>
                <td>
                  <%= render 'book_comments/index', book: book %>
                </td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<% if flash[:notice] %>
    <div class="flash" >
      <%= flash[:notice] %>
    </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render 'books/list', book:@book_new, user:@book.user %>
    </div>
        <div class="col-xs-9">
          <h2>Book detail</h2>
          <table class="table">
            <tbody>
                <tr>
                   <td>
                     <%= link_to user_path(@book.user) do %>
                       <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40,  fallback: "no_image.jpg",size: "40x40" %>
                       <%= @book.user.name %>
                     <% end %>
                   </td>
                   <td><%= link_to @book.title, book_path(@book.id) %></td>
                   <td><%= @book.body %></td>
                    <% if @book.user == current_user %>
                     <td><%= link_to edit_book_path(@book.id)  do %>
                        <span class= "btn-sm btn-success edit_book_41102">Edit</span>
                        <% end %>
                     </td>
                     <td><%= link_to book_path(@book), method: :delete, "data-confirm" => "本当に消しますか?" do %>
                        <span class= "btn-sm btn-danger destroy_book_41102">Destroy</span>
                        <% end %>
                     </td>
                    <% end %>

                    <td id='like-button_<%= @book.id %>'>
                      <%= render 'favorites/like-button', book: @book %>
                    </td>
                      <td>
                        <p id='comments_area_<%= @book.id %>', class="fa fa-comment">
                          <%= render 'book_comments/index', book: @book %>
                        </p>
                      </td>
                </tr>
            </tbody>
          </table>
          <div class="float-wrapper">
            <div id="each_comment_<%= @book.id %>">
              <%= render 'book_comments/comments', book: @book %>
            </div>
              <%= form_with(model:[@book, @book_comment], remote: true) do |f| %>
                <div class="row">
                  <div class="col-sm-12">
                    <%= f.text_area :comment, rows:'5', class: "form-control" %>
                  </div>
                </div>
                    <%= f.submit "送信" %>
              <% end %>
          </div>
  </div>
</div>