config/routes.rb
Rails.application.routes.draw do
  # get 'search/index'
  # get 'search/search'
  get 'search' => 'seaches#search'
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'
  get 'home/about'

  resources :books, only: [:new, :create, :index, :show, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: %i[create edit update destroy]
  end

  resources :users, only: [:show, :edit, :update, :index]
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true,
                    length: { maximum: 200 }
  validates :body, presence: true,
                   length: { maximum: 200 }

  def self.search(search, word)
        if search == "forward_match"
          @book = Book.where("title LIKE?","#{word}%")
        elsif search == "backward_match"
          @book = Book.where("title LIKE?","%#{word}")
        elsif search == "perfect_match"
          @book = Book.where("#{word}")
        elsif search == "partial_match"
          @book = Book.where("title LIKE?","%#{word}%")
        else
          @book = Book.all
        end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  def change
    create_table :relationships do |t|
      t.integer :follower_id
      t.integer :following_id

      t.timestamps null: false
    end

    add_index :relationships, :follower_id
    add_index :relationships, :following_id
    add_index :relationships, [:follower_id, :following_id], unique: true
  end
  
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  attachment :profile_image

  validates :name, presence: true,
                   length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def self.search(search,word)
      if search == "forward_match"
        @user = User.where("name LIKE?","#{word}%")
      elsif search == "backward_match"
        @user = User.where("name LIKE?","%#{word}")
      elsif search == "perfect_match"
        @user = User.where("#{word}")
      elsif search == "partial_match"
        @user = User.where("name LIKE?","%#{word}%")
      else
        @user = User.all
      end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

   before_action :authenticate_user!

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = 'Book was successfully created.'
        redirect_to book_path(@book.id)# 条件がtrueだったら処理1を行う
    else
      @user = current_user
      @books = Book.all
        render 'index' # 条件がfalseだったら処理2を行う
    end

  end

  def update
    @book = Book.find(params[:id])
     if  @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
        redirect_to book_path(@book.id)# 条件がtrueだったら処理1を行う
     else
        render "edit"# 条件がfalseだったら処理2を行う
     end
  end

  def destroy
    @book = Book.find_by(id: params[:id])
    @book.destroy
    redirect_to book_path
  end

  private

  def set_user
    @user = User.find([:id])
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    unless @book.favorited_by?(current_user)
      favorite = current_user.favorites.new(book_id: @book.id)
      favorite.save
      # redirect_back(fallback_location:root_path) #直前のビューページにリダイレクト
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_back(fallback_location:root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/seaches_controller.rb
class SeachesController < ApplicationController
  
  def search
    @range = params[:range]
    search = params[:search]
    word = params[:word]

    if @range == '1'
      @user = User.search(search,word)
    else
      @book = Book.search(search,word)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   before_action :authenticate_user!

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
       redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
     if  @user.update(user_params)
       flash[:notice] = 'You have updated successfully.'
         redirect_to user_path(@user.id)
     else
        render "edit"
     end
  end
  
  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/seaches_helper.rb
module SeachesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
     user == current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <title>Bookers2</title>
  </head>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="row">
      <nav class="nav navbar-nav navbar-left">
        <span class="navbar-brand" >Bookers</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Home", user_path(current_user.id), class:"glyphicon glyphicon-home home" %></li>
            <li><%= link_to 'Users', users_path, class:"glyphicon glyphicon-user users" %></li>
            <li><%= link_to 'Books',  books_path, class:"glyphicon glyphicon-book books" %></li>
            <li><%= link_to "logout", destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-log-out logout" %></li>
          <% else %>
            <li><%= link_to "Home", root_path, class:"glyphicon glyphicon-home home" %></li>
            <li><%= link_to "About",  home_about_path, class:"glyphicon glyphicon-link about" %></li>
            <li><%= link_to "Sign up", new_user_registration_path, class:"glyphicon glyphicon-edit sign_up" %></li>
            <li><%= link_to "login",  new_user_session_path, class:"glyphicon glyphicon-log-in sign_in" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

<body>
  <br>
  <br>
  <br>
  <div class="container">
    <div class="row">
      <div class="nav navbar-nav navbar-center">
        <% if user_signed_in? %>
          <%= form_with url:search_path, method: :get, local: true do |f| %>
          　<%= f.text_field :search %>
            <%= f.select 'range' ,options_for_select([['---選択してください---', ''], ['User', '1'], ['Book', '2']]) %>
            <%= f.select 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
            <%= f.submit "検索" %>
          <% end %>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>
</body>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
</html>